// <div className={styles.container}>
//   <Head>
//     <title>Create Next App</title>
//     <meta name="description" content="Generated by create next app" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>

//   <main className={styles.main}>
//     <h1 className={styles.title}>
//       Welcome to <a href="https://nextjs.org">Next.js!</a>
//     </h1>

//     <p className={styles.description}>
//       Get started by editing{' '}
//       <code className={styles.code}>pages/index.js</code>
//     </p>

//     <div className={styles.grid}>
//       <a href="https://nextjs.org/docs" className={styles.card}>
//         <h2>Documentation &rarr;</h2>
//         <p>Find in-depth information about Next.js features and API.</p>
//       </a>

//       <a href="https://nextjs.org/learn" className={styles.card}>
//         <h2>Learn &rarr;</h2>
//         <p>Learn about Next.js in an interactive course with quizzes!</p>
//       </a>

//       <a
//         href="https://github.com/vercel/next.js/tree/canary/examples"
//         className={styles.card}
//       >
//         <h2>Examples &rarr;</h2>
//         <p>Discover and deploy boilerplate example Next.js projects.</p>
//       </a>

//       <a
//         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//         className={styles.card}
//       >
//         <h2>Deploy &rarr;</h2>
//         <p>
//           Instantly deploy your Next.js site to a public URL with Vercel.
//         </p>
//       </a>
//     </div>
//   </main>

//   <footer className={styles.footer}>
//     <a
//       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//       target="_blank"
//       rel="noopener noreferrer"
//     >
//       Powered by{' '}
//       <span className={styles.logo}>
//         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//       </span>
//     </a>
//   </footer>
// </div>
// <main className="container">
//   <div className="one"></div>
//   <div className="two">
//     <a href="#">SENDY</a>
//   </div>
//   <div className="three">
//     <span>🐱 0×594...2540</span>
//     <div className="threeRight">
//       <span>
//         <svg
//           width="512px"
//           height="512px"
//           viewBox="0 0 512 512"
//           xmlns="http://www.w3.org/2000/svg"
//         >
//           <title>ionicons-v5-e</title>
//           <rect
//             x="128"
//             y="128"
//             width="336"
//             height="336"
//             rx="57"
//             ry="57"
//             style="
//               fill: none;
//               stroke: #000;
//               stroke-linejoin: round;
//               stroke-width: 32px;
//             "
//           />
//           <path
//             d="M383.5,128l.5-24a56.16,56.16,0,0,0-56-56H112a64.19,64.19,0,0,0-64,64V328a56.16,56.16,0,0,0,56,56h24"
//             style="
//               fill: none;
//               stroke: #000;
//               stroke-linecap: round;
//               stroke-linejoin: round;
//               stroke-width: 32px;
//             "
//           />
//         </svg>
//       </span>
//       <span className="threeText">|</span>
//       <span>
//         <svg
//           width="24px"
//           height="24px"
//           viewBox="0 0 24 24"
//           fill="none"
//           xmlns="http://www.w3.org/2000/svg"
//         >
//           <path
//             fillRule="evenodd"
//             clipRule="evenodd"
//             d="M18.5303 9.46967C18.8232 9.76256 18.8232 10.2374 18.5303 10.5303L12.5303 16.5303C12.2374 16.8232 11.7626 16.8232 11.4697 16.5303L5.46967 10.5303C5.17678 10.2374 5.17678 9.76256 5.46967 9.46967C5.76256 9.17678 6.23744 9.17678 6.53033 9.46967L12 14.9393L17.4697 9.46967C17.7626 9.17678 18.2374 9.17678 18.5303 9.46967Z"
//             fill="#030D45"
//           />
//         </svg>
//       </span>
//     </div>
//   </div>
//   <div className="four">
//     <div className="theme">
//       {/*<?xml version="1.0" encoding="iso-8859-1"?>
//       <!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->*/}
//       <svg
//         version="1.1"
//         id="Layer_1"
//         xmlns="http://www.w3.org/2000/svg"
//         xmlnsXlink="http://www.w3.org/1999/xlink"
//         x="0px"
//         y="0px"
//         viewBox="0 0 310 310"
//         style="enable-background: new 0 0 310 310"
//         xmlSpace="preserve"
//       >
//         <g id="XMLID_503_">
//           <path
//             id="XMLID_504_"
//             d="M155.002,90c-35.84,0-64.998,29.159-64.998,65.001c0,35.841,29.158,64.999,64.998,64.999
//             c35.842,0,65.002-29.159,65.002-64.999C220.004,119.159,190.844,90,155.002,90z M155.002,190
//             c-19.298,0-34.998-15.701-34.998-34.999c0-19.299,15.7-35.001,34.998-35.001c19.3,0,35.002,15.701,35.002,35.001
//             C190.004,174.299,174.302,190,155.002,190z"
//           />
//           <path
//             id="XMLID_507_"
//             d="M155,60c8.284,0,15-6.716,15-15V15c0-8.284-6.716-15-15-15s-15,6.716-15,15v30
//             C140,53.284,146.716,60,155,60z"
//           />
//           <path
//             id="XMLID_508_"
//             d="M155,250c-8.284,0-15,6.716-15,15v30c0,8.284,6.716,15,15,15s15-6.716,15-15v-30
//             C170,256.716,163.284,250,155,250z"
//           />
//           <path
//             id="XMLID_509_"
//             d="M295,140h-30c-8.284,0-15,6.716-15,15s6.716,15,15,15h30c8.284,0,15-6.716,15-15S303.284,140,295,140z"
//           />
//           <path
//             id="XMLID_510_"
//             d="M60,155c0-8.284-6.716-15-15-15H15c-8.284,0-15,6.716-15,15s6.716,15,15,15h30
//             C53.284,170,60,163.284,60,155z"
//           />
//           <path
//             id="XMLID_511_"
//             d="M232.781,92.218c3.838,0,7.678-1.465,10.606-4.393l21.214-21.213c5.858-5.858,5.858-15.355,0-21.213
//             c-5.857-5.858-15.354-5.857-21.213,0l-21.214,21.213c-5.858,5.858-5.858,15.355,0,21.213
//             C225.104,90.753,228.942,92.218,232.781,92.218z"
//           />
//           <path
//             id="XMLID_512_"
//             d="M66.612,222.175l-21.214,21.214c-5.858,5.858-5.858,15.355,0,21.213c2.929,2.929,6.768,4.393,10.607,4.393
//             s7.678-1.464,10.606-4.393l21.214-21.214c5.858-5.858,5.858-15.355,0-21.213C81.968,216.316,72.47,216.316,66.612,222.175z"
//           />
//           <path
//             id="XMLID_515_"
//             d="M243.388,222.175c-5.857-5.858-15.355-5.858-21.213,0c-5.858,5.858-5.858,15.355,0,21.213l21.214,21.214
//             c2.929,2.929,6.768,4.393,10.606,4.393c3.839,0,7.678-1.464,10.606-4.393c5.858-5.858,5.858-15.355,0-21.213L243.388,222.175z"
//           />
//           <path
//             id="XMLID_516_"
//             d="M66.612,87.825c2.929,2.929,6.768,4.393,10.607,4.393c3.839,0,7.678-1.464,10.606-4.394
//             c5.858-5.858,5.858-15.355,0-21.213L66.611,45.397c-5.857-5.857-15.355-5.858-21.213,0c-5.858,5.858-5.858,15.355,0,21.213
//             L66.612,87.825z"
//           />
//         </g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//         <g></g>
//       </svg>
//     </div>
//   </div>
//   <div className="five"></div>
//   <div className="six">
//     <span className="sixLeft"> Pay at once </span>
//     <span className="sixRight"> Fees breakdown</span>
//   </div>
//   <div className="seven">
//     <div className="sevenLeft">
//       <span>Choosen network</span>
//       <span className="value">Ethereum</span>
//     </div>
//     <div className="sevenRight">
//       <span>Transaction speed</span>
//       <span className="value">120 Gwei</span>
//     </div>
//   </div>
//   <div className="eight"></div>
//   <div className="nine"></div>
//   <div className="ten">
//     <div className="tenUp">
//       <div
//         style={{
//           paddingLeft: "50px",
//           paddingRight: "50px",
//           paddingTop: "8px",
//         }}
//       >
//         <span className="amount">0.00</span>
//         <span className="currency">0.00 ETH</span>
//       </div>
//       <span className="total">Total amount</span>
//       <div className="tableTen">
//         <span className="add">
//           <svg
//             width="15px"
//             height="15px"
//             viewBox="0 0 15 15"
//             fill="none"
//             xmlns="http://www.w3.org/2000/svg"
//           >
//             <path
//               fillRule="evenodd"
//               clipRule="evenodd"
//               d="M0 7.5C0 3.35786 3.35786 0 7.5 0C11.6421 0 15 3.35786 15 7.5C15 11.6421 11.6421 15 7.5 15C3.35786 15 0 11.6421 0 7.5ZM7 11V8H4V7H7V4H8V7H11V8H8V11H7Z"
//               fill="black"
//             />
//           </svg>
//         </span>
//         <div className="table">
//           <div className="tenTableLeft">
//             <div className="selection">
//               <span>
//                 <svg
//                   width="64px"
//                   height="64px"
//                   viewBox="0 0 64 64"
//                   xmlns="http://www.w3.org/2000/svg"
//                   xmlnsXlink="http://www.w3.org/1999/xlink"
//                   ariaHidden="true"
//                   role="img"
//                   className="iconify iconify--emojione"
//                   preserveAspectRatio="xMidYMid meet"
//                 >
//                   <circle cx="32" cy="32" r="30" fill="#4fd1d9"></circle>
//                   <path
//                     d="M25.8 37.6c.2 1.3.6 2.3 1.1 3c1 1.2 2.7 1.8 5.2 1.8c1.5 0 2.6-.2 3.6-.5c1.7-.6 2.6-1.7 2.6-3.4c0-1-.4-1.7-1.3-2.2c-.8-.5-2.2-1-4-1.4l-3.1-.7c-3.1-.7-5.2-1.4-6.4-2.2c-2-1.3-2.9-3.4-2.9-6.3c0-2.6 1-4.8 2.9-6.5c1.9-1.7 4.7-2.6 8.4-2.6c3.1 0 5.7.8 7.9 2.4c2.2 1.6 3.3 4 3.4 7.1h-5.8c-.1-1.7-.9-3-2.3-3.7c-1-.5-2.2-.7-3.6-.7c-1.6 0-2.9.3-3.8.9s-1.4 1.5-1.4 2.6c0 1 .5 1.8 1.4 2.3c.6.3 1.9.7 3.9 1.2l5.1 1.2c2.2.5 3.9 1.2 5 2.1c1.7 1.4 2.6 3.3 2.6 5.9c0 2.7-1 4.9-3.1 6.6c-2 1.8-4.9 2.6-8.7 2.6c-3.8 0-6.8-.9-9-2.6c-2.4-1.5-3.5-3.9-3.5-6.9h5.8"
//                     fill="#fff"
//                   ></path>
//                 </svg>
//               </span>
//               Select token
//             </div>
//             <span>
//               <svg
//                 width="24px"
//                 height="24px"
//                 viewBox="0 0 24 24"
//                 fill="none"
//                 xmlns="http://www.w3.org/2000/svg"
//               >
//                 <path
//                   fillRule="evenodd"
//                   clipRule="evenodd"
//                   d="M18.5303 9.46967C18.8232 9.76256 18.8232 10.2374 18.5303 10.5303L12.5303 16.5303C12.2374 16.8232 11.7626 16.8232 11.4697 16.5303L5.46967 10.5303C5.17678 10.2374 5.17678 9.76256 5.46967 9.46967C5.76256 9.17678 6.23744 9.17678 6.53033 9.46967L12 14.9393L17.4697 9.46967C17.7626 9.17678 18.2374 9.17678 18.5303 9.46967Z"
//                   fill="#030D45"
//                 />
//               </svg>
//             </span>
//           </div>
//           <div className="tenTableRight">
//             <div className="information">
//               Deflationary
//               <span>
//                 {/*
//                <?xml version="1.0" encoding="iso-8859-1"?>
//                 <!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  --> */}
//                 <svg
//                   version="1.1"
//                   id="Capa_1"
//                   xmlns="http://www.w3.org/2000/svg"
//                   xmlnsXlink="http://www.w3.org/1999/xlink"
//                   x="0px"
//                   y="0px"
//                   viewBox="0 0 23.625 23.625"
//                   style="enable-background: new 0 0 23.625 23.625"
//                   xmlSpace="preserve"
//                 >
//                   <g>
//                     <path
//                       style="fill: #030104"
//                       d="M11.812,0C5.289,0,0,5.289,0,11.812s5.289,11.813,11.812,11.813s11.813-5.29,11.813-11.813
//                         S18.335,0,11.812,0z M14.271,18.307c-0.608,0.24-1.092,0.422-1.455,0.548c-0.362,0.126-0.783,0.189-1.262,0.189
//                         c-0.736,0-1.309-0.18-1.717-0.539s-0.611-0.814-0.611-1.367c0-0.215,0.015-0.435,0.045-0.659c0.031-0.224,0.08-0.476,0.147-0.759
//                         l0.761-2.688c0.067-0.258,0.125-0.503,0.171-0.731c0.046-0.23,0.068-0.441,0.068-0.633c0-0.342-0.071-0.582-0.212-0.717
//                         c-0.143-0.135-0.412-0.201-0.813-0.201c-0.196,0-0.398,0.029-0.605,0.09c-0.205,0.063-0.383,0.12-0.529,0.176l0.201-0.828
//                         c0.498-0.203,0.975-0.377,1.43-0.521c0.455-0.146,0.885-0.218,1.29-0.218c0.731,0,1.295,0.178,1.692,0.53
//                         c0.395,0.353,0.594,0.812,0.594,1.376c0,0.117-0.014,0.323-0.041,0.617c-0.027,0.295-0.078,0.564-0.152,0.811l-0.757,2.68
//                         c-0.062,0.215-0.117,0.461-0.167,0.736c-0.049,0.275-0.073,0.485-0.073,0.626c0,0.356,0.079,0.599,0.239,0.728
//                         c0.158,0.129,0.435,0.194,0.827,0.194c0.185,0,0.392-0.033,0.626-0.097c0.232-0.064,0.4-0.121,0.506-0.17L14.271,18.307z
//                          M14.137,7.429c-0.353,0.328-0.778,0.492-1.275,0.492c-0.496,0-0.924-0.164-1.28-0.492c-0.354-0.328-0.533-0.727-0.533-1.193
//                         c0-0.465,0.18-0.865,0.533-1.196c0.356-0.332,0.784-0.497,1.28-0.497c0.497,0,0.923,0.165,1.275,0.497
//                         c0.353,0.331,0.53,0.731,0.53,1.196C14.667,6.703,14.49,7.101,14.137,7.429z"
//                     />
//                   </g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                   <g></g>
//                 </svg>
//               </span>
//             </div>
//             <label className="switch">
//               <input type="checkbox" checked />
//               <div className="slider">
//                 <span className="on"></span>
//                 <span className="off"></span>
//               </div>
//             </label>
//           </div>
//           <div className="tenFirstColumn">
//             <div className="tenOne">Address</div>
//             <div className="tenTwo">Amount</div>
//             <div className="tenThree">Email(Optional)</div>
//             <div className="tenFour">0×203...dfa7</div>
//             <div className="tenFive">7,500</div>
//             <div className="tenSix">example@email.com</div>
//             <div className="tenSeven">0×203...dfa7</div>
//             <div className="tenEight">7,500</div>
//             <div className="tenNine">example@email.com</div>
//             <div className="tenTen">0×203...dfa7</div>
//             <div className="tenEleven">7,500</div>
//             <div className="tenTwelve">example@email.com</div>
//             <div className="tenThirteen">0×203...dfa7</div>
//             <div className="tenFourteen">7,500</div>
//             <div className="tenFifteen">example@email.com</div>
//           </div>
//           <div className="tenSecondColumn">
//             <div className="tenOne">Name(Optional)</div>
//             <div className="tenTwo">Notes(Optional)</div>
//             <div className="tenThree">Pollen TG</div>
//             <div className="tenFour">March 2022 bill</div>
//             <div className="tenFive">Pollen TG</div>
//             <div className="tenSix">March 2022 bill</div>
//             <div className="tenSeven">Pollen TG</div>
//             <div className="tenEight">March 2022 bill</div>
//             <div className="tenNine">Pollen TG</div>
//             <div className="tenTen">March 2022 bill</div>
//           </div>
//         </div>
//       </div>
//     </div>
//     <div className="tenDown">
//       <div>
//         <span>
//           <svg
//             width="48px"
//             height="48px"
//             viewBox="0 0 48 48"
//             version="1"
//             xmlns="http://www.w3.org/2000/svg"
//             enableBackground="new 0 0 48 48"
//           >
//             <path
//               fill="#009688"
//               d="M36,45H12c-2.2,0-4-1.8-4-4V7c0-2.2,1.8-4,4-4h16.3c1.1,0,2.1,0.4,2.8,1.2l7.7,7.7c0.8,0.8,1.2,1.8,1.2,2.8 V41C40,43.2,38.2,45,36,45z"
//             />
//             <path
//               fill="#FF9800"
//               d="M32,38H16c-1.1,0-2-0.9-2-2V24c0-1.1,0.9-2,2-2h16c1.1,0,2,0.9,2,2v12C34,37.1,33.1,38,32,38z"
//             />
//             <path
//               fill="#FFD54F"
//               d="M29,30v3h5v2h-5v3h-2V22h2v6h5v2H29z M14,29v2h5v2h-5v2h5v3h2v-9H14z"
//             />
//           </svg>
//         </span>
//         Connect Google
//       </div>
//       <span className="textTenDown">|</span>
//       <div>
//         <span>
//           {/*
//           <?xml version="1.0" encoding="iso-8859-1"?>
//           <!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  --> */}
//           <svg
//             version="1.1"
//             id="Capa_1"
//             xmlns="http://www.w3.org/2000/svg"
//             xmlnsXlink="http://www.w3.org/1999/xlink"
//             x="0px"
//             y="0px"
//             viewBox="0 0 184.979 184.979"
//             style="enable-background: new 0 0 184.979 184.979"
//             xmlSpace="preserve"
//           >
//             <g>
//               <g>
//                 <path
//                   style="fill: #010002"
//                   d="M121.539,122.24c0.585,0.585,1.349,0.871,2.112,0.871c0.764,0,1.528-0.292,2.112-0.871
//                         c1.164-1.164,1.164-3.055,0-4.219L94.605,86.869c0,0,0,0-0.006-0.006l-2.106-2.106l-2.106,2.106c0,0,0,0-0.006,0.006
//                         l-31.159,31.153c-1.164,1.164-1.164,3.055,0,4.219c1.164,1.164,3.055,1.164,4.219,0l26.069-26.063v52.556
//                         c0,1.647,1.337,2.983,2.983,2.983c1.647,0,2.983-1.337,2.983-2.983V96.177L121.539,122.24z"
//                 />
//                 <path
//                   style="fill: #010002"
//                   d="M151.057,67.673C143.712,47.01,124.32,33.25,102.236,33.25c-20.812,0-39.531,12.518-47.628,31.493
//                         c-3.813-1.766-7.96-2.685-12.172-2.685c-16.051,0-29.118,13.044-29.148,29.088C4.941,97.531,0,107.448,0,117.998
//                         c0,18.593,15.168,33.719,34.31,33.725c0.215,0,0.43,0.006,0.621,0.006c0.203,0,0.382,0,0.525-0.012h31.445
//                         c1.647,0,2.983-1.337,2.983-2.983s-1.337-2.983-2.983-2.983H35.3c-0.292,0.018-0.597,0.006-0.889,0l-0.609-0.006
//                         c-15.347,0-27.835-12.447-27.835-27.752c0-9.147,4.511-17.722,12.065-22.925l1.372-1.366l-0.149-2.494
//                         c0-12.781,10.4-23.181,23.181-23.181c4.284,0,8.491,1.205,12.166,3.479l3.156,1.957l1.229-3.509
//                         c6.432-18.384,23.808-30.729,43.254-30.729c20.073,0,37.639,12.847,43.707,31.976l0.555,1.748l1.814,0.292
//                         c17.781,2.876,30.694,18.032,30.694,36.04c0,20.114-16.403,36.475-36.559,36.475h-24.375c-1.647,0-2.983,1.337-2.983,2.983
//                         s1.337,2.983,2.983,2.983h24.375c23.45,0,42.526-19.04,42.526-42.442C184.973,88.933,170.814,71.719,151.057,67.673z"
//                 />
//               </g>
//             </g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//             <g></g>
//           </svg>
//         </span>
//         Upload CSV
//       </div>
//     </div>
//   </div>
//   <div className="eleven">
//     <div className="firstEleven">
//       <span>Network</span>
//       <span>Gas fee</span>
//     </div>
//     <div className="secondEleven">
//       <h4>Choose network</h4>
//       <p>
//         Ensure the network you choose to deposit matches the withdrawal
//         network, or assets may be lost.
//       </p>
//       <div className="elevenLeft">
//         <section>
//           <span>
//             <svg
//               xmlns="http://www.w3.org/2000/svg"
//               ariaLabel="Ethereum"
//               role="img"
//               viewBox="0 0 512 512"
//             >
//               <rect width="512" height="512" rx="15%" fill="#fff" />
//               <path fill="#3C3C3B" d="m256 362v107l131-185z" />
//               <path fill="#343434" d="m256 41l131 218-131 78-132-78" />
//               <path
//                 fill="#8C8C8C"
//                 d="m256 41v158l-132 60m0 25l132 78v107"
//               />
//               <path fill="#141414" d="m256 199v138l131-78" />
//               <path fill="#393939" d="m124 259l132-60v138" />
//             </svg>
//           </span>
//           Ethereum
//         </section>
//         <span>
//           {/* <?xml version="1.0" ?> */}
//           <svg
//             width="200px"
//             height="200px"
//             viewBox="0 0 200 200"
//             dataName="Layer 1"
//             id="Layer_1"
//             xmlns="http://www.w3.org/2000/svg"
//           >
//             <title />
//             <path d="M177.6,80.43a10,10,0,1,0-19.5,4.5,60.76,60.76,0,0,1-6,44.5c-16.5,28.5-53.5,38.5-82,22-28.5-16-38.5-53-22-81.5s53.5-38.5,82-22a9.86,9.86,0,1,0,10-17c-38.5-22.5-87-9.5-109.5,29a80.19,80.19,0,1,0,147,20.5Zm-109.5,11a10.12,10.12,0,0,0-11,17l40,25a10.08,10.08,0,0,0,5.5,1.5,10.44,10.44,0,0,0,8-4l52.5-67.5c3.5-4.5,2.5-10.5-2-14s-10.5-2.5-14,2l-47,60Z" />
//           </svg>
//         </span>
//       </div>
//       <div className="elevenRight">
//         <span>
//           <svg
//             width="36px"
//             height="36px"
//             viewBox="0 0 36 36"
//             xmlns="http://www.w3.org/2000/svg"
//             xmlnsXlink="http://www.w3.org/1999/xlink"
//             ariaHidden="true"
//             role="img"
//             className="iconify iconify--twemoji"
//             preserveAspectRatio="xMidYMid meet"
//           >
//             <circle fill="#3B94D9" cx="18" cy="18" r="18"></circle>
//             <path
//               fill="#FFF"
//               d="M25.565 11.295c-2.116 0-4.195 1.322-5.799 2.712a21.08 21.08 0 0 1 1.147 1.364c.172.227.423.534.733.882c1.236-1.084 2.689-2.044 3.919-2.044c2.09 0 3.79 1.7 3.79 3.79s-1.7 3.79-3.79 3.79c-2.337 0-5.484-3.456-6.402-4.668c-.45-.596-4.521-5.826-8.729-5.826c-3.697 0-6.705 3.008-6.705 6.705s3.008 6.704 6.705 6.704c2.055 0 4.073-1.248 5.657-2.594a21.026 21.026 0 0 1-1.255-1.483a14.747 14.747 0 0 0-.624-.757c-1.204 1.032-2.594 1.919-3.778 1.919c-2.09 0-3.79-1.7-3.79-3.79s1.7-3.79 3.79-3.79c2.338 0 5.484 3.456 6.402 4.668c.45.596 4.521 5.826 8.729 5.826a6.711 6.711 0 0 0 6.704-6.704a6.71 6.71 0 0 0-6.704-6.704z"
//             ></path>
//           </svg>
//         </span>
//         Polygon
//       </div>
//     </div>
//     <div className="thirdEleven">
//       <span>
//         <svg
//           width="1024px"
//           height="1024px"
//           viewBox="0 0 1024 1024"
//           xmlns="http://www.w3.org/2000/svg"
//         >
//           <style>{".st1{ fill: #fff }"}</style>
//           <g id="Icon">
//             <circle cx="512" cy="512" r="512" style="fill: #f3ba2f" />
//             <path
//               className="st1"
//               d="M404.9 468 512 360.9l107.1 107.2 62.3-62.3L512 236.3 342.6 405.7z"
//             />
//             <path
//               transform="rotate(-45.001 298.629 511.998)"
//               className="st1"
//               d="M254.6 467.9h88.1V556h-88.1z"
//             />
//             <path
//               className="st1"
//               d="M404.9 556 512 663.1l107.1-107.2 62.4 62.3h-.1L512 787.7 342.6 618.3l-.1-.1z"
//             />
//             <path
//               transform="rotate(-45.001 725.364 512.032)"
//               className="st1"
//               d="M681.3 468h88.1v88.1h-88.1z"
//             />
//             <path
//               className="st1"
//               d="M575.2 512 512 448.7l-46.7 46.8-5.4 5.3-11.1 11.1-.1.1.1.1 63.2 63.2 63.2-63.3z"
//             />
//           </g>
//         </svg>
//       </span>
//       Binance Chain
//     </div>
//     <div className="fourthEleven">
//       <span>
//         {/*  <?xml version="1.0" ?> */}
//         <svg
//           width="200px"
//           height="200px"
//           viewBox="0 0 200 200"
//           dataName="Layer 1"
//           id="Layer_1"
//           xmlns="http://www.w3.org/2000/svg"
//         >
//           <title />
//           <path d="M75,20H40A20.06,20.06,0,0,0,20,40V75A20.06,20.06,0,0,0,40,95H75A20.06,20.06,0,0,0,95,75V40A20.06,20.06,0,0,0,75,20Zm0,55H40V40H75Zm95-27.5a10,10,0,0,0-10,10V75H125V40h17.5a10,10,0,0,0,0-20H125a20.06,20.06,0,0,0-20,20V75a20.06,20.06,0,0,0,20,20h35a20.06,20.06,0,0,0,20-20V57.5A10,10,0,0,0,170,47.5ZM75,105H40a20.06,20.06,0,0,0-20,20v35a20.06,20.06,0,0,0,20,20H75a20.06,20.06,0,0,0,20-20V125A20.06,20.06,0,0,0,75,105Zm0,55H40V125H75Zm85-55H125a20.06,20.06,0,0,0-20,20v35a20.06,20.06,0,0,0,20,20h35a20.06,20.06,0,0,0,20-20V125A20.06,20.06,0,0,0,160,105Zm0,55H125V125h35Z" />
//         </svg>{" "}
//       </span>
//       More Networks
//     </div>
//   </div>
//   <div className="twelve"></div>
//   <div className="thirteen"></div>
//   <div className="fourteen">
//     <button type="button" className="btnClear">
//       Clear
//     </button>
//     <button type="button" className="btnNext">
//       Next
//     </button>
//   </div>
//   <div className="fifteen">
//     <div></div>
//   </div>
//   <div className="sixteen">
//     <div></div>
//   </div>
// </main>
